[theme]
base="light"                     # "light" oder "dark"
primaryColor="#5B7CFA"           # Buttons, Highlights
backgroundColor="#F7F8FB"        # Hauptfläche
secondaryBackgroundColor="#FFFFFF" # Karten/Sidebar
textColor="#0E1116"
font="sans serif"                # ("sans serif", "serif", "mono")